# Generated by Django 3.0.4 on 2020-05-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_auto_20200518_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-distance_in_feet',)},
        ),
    ]
