# Generated by Django 3.0.4 on 2020-05-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_auto_20200518_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='dronecategory',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
