# Generated by Django 3.0.4 on 2020-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('toy_category', models.CharField(default='', max_length=200)),
                ('was_included_in_home', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Toy',
                'verbose_name_plural': 'Toys',
                'ordering': ('name',),
            },
        ),
    ]
